services:
  flask-app:
    build:
      context: ./python
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=db
      - DB_USER=postgres
      - DB_PASSWORD=prodigy
      - DB_HOST=postgres
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx
      dockerfile: DockerfileDev
    ports:
      - "8080:80"
    depends_on:
      - flask-app
    

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=prodigy
      - POSTGRES_HOST_AUTH_METHOD=trust
 
