services:
  flask-app:
    build:
      context: ./python
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=db
      - DB_USER=postgres
      - DB_PASSWORD=prodigy
      - DB_HOST=postgres
    depends_on:
      - postgres

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask-app      
    volumes:
      - /etc/letsencrypt/live/kimbi.hackster.me/fullchain.pem:/etc/letsencrypt/live/kimbi.hackster.me/fullchain.pem
      - /etc/letsencrypt/live/kimbi.hackster.me/privkey.pem:/etc/letsencrypt/live/kimbi.hackster.me/privkey.pem
      - /etc/ssl/certs/dhparam.pem:/etc/ssl/certs/dhparam.pem
      
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prodigy
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: