apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
        listen {{ .Values.nginx.service.port }};
        server_name {{ .Values.nginx.serverName }};

        location / {
            root   {{ .Values.nginx.rootPath }};
            index  {{- range .Values.nginx.indexFiles }} {{ . }} {{- end }};
        }
    }