apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.python.name }}
  labels:
    {{- include "button.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.python.replicaCount }}
  selector:
    matchLabels:
      {{- include "button.selectorLabels" . | nindent 6 }}
      app: {{ .Values.python.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "button.selectorLabels" . | nindent 8 }}
        app: {{ .Values.python.name }}

    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.python.image.repository }}:{{ .Values.python.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.python.image.pullPolicy }}
          command: ["python3"]
          args: ["app.py"]
          ports:
            - name: http
              containerPort: {{ .Values.python.service.port | default 5000 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          env:
            {{- if .Values.python.envs }}
            {{- toYaml .Values.python.envs | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}