imagePullSecrets:
  - name: your-regcred
  
ingress:
  enabled: true
  className: nginx
  annotations: 
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: kimbi.hackster.me
      paths:
        - path: /
          pathType: Prefix
          service:
            name: nginx
            port: 80
        - path: /api
          pathType: Prefix
          service:
            name: python-deployment
            port: 5000
  tls: 
    - secretName: nginx-tls-secret
      hosts:

nginx:
  image:
    repository: kimbiharbor.hackster.me/application/nginx
    tag: v2
  replicaCount: 1
  name: nginx
  serverName: kimbi.hackster.me
  rootPath: "/usr/share/nginx/html"
  mountPath: "/etc/nginx/conf.d"
  indexFiles:
    - "index.html"
    - "index.htm"
  service:
    type: ClusterIP
    port: 80

resources: 
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 100m
    memory: 64Mi


python:
  image:
    repository: kimbiharbor.hackster.me/application/python
    tag: v2
  name: python
  envs:
    - name: DB_HOST
      value: "postgresql.default.svc.cluster.local" 
    - name: DB_NAME
      value: dbname
    - name: DB_USER
      value: youruser
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgresql
          key: password
  service: 
    type: ClusterIP
    port: 5000