name: Build and Push Nginx to Harbor

on:
  # 1 
  push:
    paths:
      - 'k8s/nginx/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # 2
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # 3
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git symbolic-ref --short HEAD)-$(git rev-parse --short HEAD)-$(date +%s)"

    # 4
    - name: Build and Push Docker Image
      env:
        # 5
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        HARBOR_ENDPOINT: ${{ secrets.HARBOR_ENDPOINT }}
        IMAGE_TAG: ${{ steps.vars.outputs.sha_short }}
      # 6
      run: |
        cd k8s/nginx
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $HARBOR_ENDPOINT
        docker build -t $HARBOR_ENDPOINT/application/nginx:$IMAGE_TAG . --push